name: "Build and Release"

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"

jobs:
  aria2c_zlib_and_libexpat:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          # DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y
          apt-get install -y --no-install-recommends \
              make binutils autoconf automake autotools-dev libtool \
              patch ca-certificates \
              pkg-config git wget curl dpkg-dev \
              autopoint libcppunit-dev lzip jq unzip lld rsync
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build.sh"
          "${GITHUB_WORKSPACE}/build.sh"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: "${{ github.workspace }}/*.{exe,md}"
  aria2c1_zlib_ng_and_libxml2:
    runs-on: ubuntu-24.04
    #container: "rzhy/ubuntu:x86_64-w64-mingw32"
    container:
      image: ubuntu:rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
              automake  autoconf autopoint jq libtool \
              make pkgconf wget curl tcl \
              ca-certificates unzip lld rsync
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build1.sh"
          "${GITHUB_WORKSPACE}/build1.sh"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts1
          path: "${{ github.workspace }}/*.{exe,md}"
  release :
    runs-on: ubuntu-24.04
    needs: [aria2c_zlib_and_libexpat, aria2c1_zlib_ng_and_libxml2]
    if: always()
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: release-folder
        continue-on-error: true
      - name: Download artifacts1
        uses: actions/download-artifact@v4
        with:
          name: artifacts1
          path: release-folder
        continue-on-error: true
      - name: Merge release notes
        run: |
          mkdir -p ${{ github.workspace }}/release-folder
          cat release-folder/*.md > ${{ github.workspace }}/release-folder/release_notes.md
      - name: Get Version
        run: |
          VERSION=$(wget -qO- https://raw.githubusercontent.com/aria2/aria2/master/NEWS | grep -oP 'aria2 \K\d+(\.\d+)*')
          echo "ARIA2_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: aria2c-${{ env.ARIA2_VERSION }}
          allowUpdates: true
          artifacts: ${{ github.workspace }}/release-folder/aria2c.exe, ${{ github.workspace }}/release-folder/aria2c1.exe
          bodyFile: ${{ github.workspace }}/release-folder/release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
    
