name: "Build and Release"

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-aria2c:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          # DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y
          apt-get install -y --no-install-recommends \
              make binutils autoconf automake autotools-dev libtool \
              patch ca-certificates \
              pkg-config git wget curl dpkg-dev \
              autopoint libcppunit-dev lzip jq unzip zstd lld rsync bc
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build.sh"
          "${GITHUB_WORKSPACE}/build.sh"
      - name: Archive aria2c.exe
        uses: actions/upload-artifact@v4
        with:
          name: aria2c.exe
          path: "${{ github.workspace }}/aria2c.exe"
      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: "${{ github.workspace }}/build_info.md"
  build-aria2c1:
    runs-on: ubuntu-24.04
    #container: "rzhy/ubuntu:x86_64-w64-mingw32"
    container:
      image: ubuntu:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
              automake  autoconf autopoint jq libtool \
              make pkgconf wget curl tcl \
              ca-certificates unzip zstd lld rsync bc
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build1.sh"
          "${GITHUB_WORKSPACE}/build1.sh"
      - name: Archive aria2c1.exe
        uses: actions/upload-artifact@v4
        with:
          name: aria2c1.exe
          path: "${{ github.workspace }}/aria2c1.exe"
      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info1
          path: "${{ github.workspace }}/build_info1.md"


  Release:
    runs-on: ubuntu-24.04
    needs: [build-aria2c, build-aria2c1]
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
           path: release-folder1
        continue-on-error: true
      - name: Create Release Notes File
        run: |
          mkdir -p release-folder
          find release-folder1 -type f -exec sh -c 'mv {} release-folder' \;
          cat release-folder/*.md > ${{ github.workspace }}/release-folder/release_notes.md
      - name: Get Aria2 Version
        run: |
          VERSION=$(wget -qO- https://raw.githubusercontent.com/aria2/aria2/master/NEWS | grep -oP 'aria2 \K\d+(\.\d+)*')
          echo "ARIA2_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: aria2c-${{ env.ARIA2_VERSION }}
          allowUpdates: true
          artifacts: ${{ github.workspace }}/release-folder/*.exe
          bodyFile: ${{ github.workspace }}/release-folder/release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
