name: "Build and Release"
#dsafasfdsafdsaf
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-aria2c:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Find fastest apt mirror (simplified)
        run: |
          echo "Testing mirror speeds (simplified)..."
          
          # 镜像列表和对应的测试URL
          declare -A MIRROR_URLS=(
          	["archive.ubuntu.com"]="http://archive.ubuntu.com/ubuntu/dists/noble/Release.gpg"
          	["ports.ubuntu.com"]="http://ports.ubuntu.com/ubuntu-ports/dists/noble/Release.gpg"
          	["security.ubuntu.com"]="http://security.ubuntu.com/ubuntu/dists/noble/Release.gpg"
          	["mirrors.mit.edu"]="http://mirrors.mit.edu/ubuntu/dists/noble/Release.gpg"
          	["mirror.csclub.uwaterloo.ca"]="http://mirror.csclub.uwaterloo.ca/ubuntu/dists/noble/Release.gpg"
          	["ubuntu.mirror.ac.za"]="http://ubuntu.mirror.ac.za/ubuntu/dists/noble/Release.gpg"
          	["ubuntu.mirror.digitalpacific.com.au"]="http://ubuntu.mirror.digitalpacific.com.au/ubuntu/dists/noble/Release.gpg"
          	["mirror.lagoon.nc"]="http://mirror.lagoon.nc/ubuntu/dists/noble/Release.gpg"
          	["ubuntu.mirror.rafal.ca"]="http://ubuntu.mirror.rafal.ca/ubuntu/dists/noble/Release.gpg"
          	["mirrors.coreix.net"]="http://mirrors.coreix.net/ubuntu/dists/noble/Release.gpg"
          	["mirror.koddos.net"]="http://mirror.koddos.net/ubuntu/dists/noble/Release.gpg"
          	["ftp.rrze.de"]="http://ftp.rrze.de/ubuntu/dists/noble/Release.gpg"
          	["mirrors.dotsrc.org"]="http://mirrors.dotsrc.org/ubuntu/dists/noble/Release.gpg"
          	["ubuntu.mirror.nforce.com"]="http://ubuntu.mirror.nforce.com/ubuntu/dists/noble/Release.gpg"
          	["mirror.enzu.com"]="http://mirror.enzu.com/ubuntu/dists/noble/Release.gpg"
          	["mirrors.tencent.com"]="http://mirrors.tencent.com/ubuntu/dists/noble/Release.gpg"
          	["mirrors.aliyun.com"]="http://mirrors.aliyun.com/ubuntu/dists/noble/Release.gpg"
          	["mirrors.tuna.tsinghua.edu.cn"]="http://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/noble/Release.gpg"
          	["mirrors.ustc.edu.cn"]="http://mirrors.ustc.edu.cn/ubuntu/dists/noble/Release.gpg"
          	["mirrors.huaweicloud.com"]="http://mirrors.huaweicloud.com/ubuntu/dists/noble/Release.gpg"
          	["mirrors.bfsu.edu.cn"]="http://mirrors.bfsu.edu.cn/ubuntu/dists/noble/Release.gpg"
          	["mirrors.sjtug.sjtu.edu.cn"]="http://mirrors.sjtug.sjtu.edu.cn/ubuntu/dists/noble/Release.gpg"
          )
          
          FASTEST_MIRROR=""
          FASTEST_TIME=999999
          
          for mirror in "${!MIRROR_URLS[@]}"; do
            echo -n "Testing $mirror ... "
            URL="${MIRROR_URLS[$mirror]}"
            
            # 使用timeout确保不会卡住
            START_TIME=$(date +%s%3N)
            if timeout 10s curl --connect-timeout 5 --silent --output /dev/null "$URL"; then
              END_TIME=$(date +%s%3N)
              TIME_MS=$((END_TIME - START_TIME))
              echo "${TIME_MS}ms"
              
              if [ "$TIME_MS" -lt "$FASTEST_TIME" ]; then
                FASTEST_MIRROR="$mirror"
                FASTEST_TIME="$TIME_MS"
              fi
            else
              echo "failed"
            fi
          done
          
          if [ -n "$FASTEST_MIRROR" ]; then
            echo "Fastest mirror: $FASTEST_MIRROR (${FASTEST_TIME}ms)"
            echo "FASTEST_MIRROR=$FASTEST_MIRROR" >> $GITHUB_ENV
          else
            echo "No working mirror found, using default"
            echo "FASTEST_MIRROR=archive.ubuntu.com" >> $GITHUB_ENV
          fi
      - name: Install prerequisites
        run: |
          sudo apt-get update
          # DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y
          sudo apt-get install -y --no-install-recommends \
              make binutils autoconf automake autotools-dev libtool \
              patch ca-certificates g++-mingw-w64-x86-64 \
              pkg-config git wget curl dpkg-dev \
              autopoint libcppunit-dev lzip jq unzip lld zstd rsync bc
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build.sh"
          "${GITHUB_WORKSPACE}/build.sh"
          
      - name: Output config.log (Always)
        if: always()
        run: |
          if [ -f aria2/config.log ]; then
              echo "Config.log content:"
              cat aria2/config.log
          else
              echo "config.log not found"
          fi
          
      - name: Archive aria2c.exe
        uses: actions/upload-artifact@v5
        with:
          name: aria2c.exe
          path: "${{ github.workspace }}/aria2c.exe"
      - name: Upload build info
        uses: actions/upload-artifact@v5
        with:
          name: build-info
          path: "${{ github.workspace }}/build_info.md"
  build-aria2c1:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
              automake  autoconf autopoint jq libtool tcl tcl-dev \
              make pkg-config wget curl git \
              ca-certificates libcppunit-dev unzip lld zstd rsync bc
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build1.sh"
          "${GITHUB_WORKSPACE}/build1.sh"
      - name: Upload sqlite config.log on failure
        if: failure() # 关键！同样只在失败时运行
        uses: actions/upload-artifact@v5 # 使用官方的上传工具
        with:
          name: sqlite-config-log # 上传后压缩包的名字
          path: /usr/src/sqlite-*/config.log # 要上传的文件的路径
      - name: Archive aria2c1.exe
        uses: actions/upload-artifact@v5
        with:
          name: aria2c1.exe
          path: "${{ github.workspace }}/aria2c1.exe"
      - name: Upload build info
        uses: actions/upload-artifact@v5
        with:
          name: build-info1
          path: "${{ github.workspace }}/build_info1.md"


  Release:
    runs-on: ubuntu-24.04
    needs: [build-aria2c, build-aria2c1]
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
           path: release-folder
           merge-multiple: true
        continue-on-error: true
      - name: Create Release Notes File
        run: |
          cat release-folder/*.md > ${{ github.workspace }}/release-folder/release_notes.md
      - name: Get Aria2 Version
        run: |
          VERSION=$(wget -qO- https://raw.githubusercontent.com/aria2/aria2/master/NEWS | grep -oP 'aria2 \K\d+(\.\d+)*')
          echo "ARIA2_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: aria2c-${{ env.ARIA2_VERSION }}
          allowUpdates: true
          artifacts: ${{ github.workspace }}/release-folder/*.exe
          bodyFile: ${{ github.workspace }}/release-folder/release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
