name: "Build and Release"

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  schedule:
    - cron: "0 0 * * 6"

jobs:
  static-build:
    runs-on: ubuntu-24.04
    container: "abcfy2/muslcc-toolchain-ubuntu:x86_64-w64-mingw32"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: downloads/
          key: build-cache-x86_64-w64-mingw32-${{ github.sha }}
          restore-keys: |
            build-cache-x86_64-w64-mingw32-
      - name: compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          if [ "${GITHUB_EVENT_NAME}" = release ]; then
            export ARIA2_VER="${GITHUB_REF#refs/*/}"
            echo "ARIA2_VER=${ARIA2_VER}" >> $GITHUB_ENV
          fi
          "${GITHUB_WORKSPACE}/build.sh"
      - name: Archive aria2c.exe
        uses: actions/upload-artifact@v4
        with:
          name: aria2c.exe
          path: "${GITHUB_WORKSPACE}"/aria2c*
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: aria2c
          allowUpdates: true
          artifacts: "${GITHUB_WORKSPACE}"/aria2c*
          bodyFile: "${{ github.workspace }}/build_info.md"
          token: ${{ secrets.GITHUB_TOKEN }}
